### ISSUE TITLE
Playlist Add Icon not working as expected

### ISSUE THREAD

**Issue by abhisheknaiidu** [BITSoC/A-POP#21]
After merging, #18 by @zee-bit, the Playlist add icon is not in sync with the delete button in the playlist, 
when we delete a particular song from playlist, the Playlist icon shows marked only.

**Expected Behaviour** - Should be in sync with Delete Button  as well.

**Comment by sv-benzez** [comment]
Just my 2 cents here,
I think SongList could query GET_PLAYLIST_SONGS to know witch songs are currently in the playlist, instead of managing a local state that cannot be accessed by SongPlayer ?

However, I'm not sure about performance.

@abhisheknaiidu , @zee-bit, can I give it a try ?

**Comment by abhisheknaiidu** [comment]
@sv-benzez sure!
