### ISSUE TITLE
Adding pull request template and issue template

### ISSUE THREAD

**Issue by iamrajiv** [BITSoC/A-POP#24]
Reference: https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by iamrajiv** [comment]
@abhisheknaiidu I want to work on this issue.

**Comment by abhisheknaiidu** [comment]
@iamrajiv Sure, but try to take help from this - https://github.com/open-sauced/open-sauced/tree/main/.github
they have used many Emoji's to make Templates.
